# Generated by Django 4.2.1 on 2023-06-05 18:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("dictionary", "0003_definition_slug"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="definition",
            name="example",
        ),
    ]
